const ActionEnums = Object.freeze({
    APP_STATE_SET_START_GAME: "APP_STATE_SET_START_GAME",
    ALGORITHM_STATE_SET_IS_SELECTED: "ALGORITHM_STATE_SET_IS_SELECTED",
    ALGORITHM_STATE_RESTORE_DATA: "ALGORITHM_STATE_RESTORE_DATA",
    GAME_STATE_SET_AREA_SEARCH: "GAME_STATE_SET_AREA_SEARCH",
    GAME_STATE_SET_BOARD_SIZE: "GAME_STATE_SET_BOARD_SIZE",
    GAME_STATE_SET_TARGET_POSITION: "GAME_STATE_SET_TARGET_POSITION",
    GAME_STATE_SET_OPTIMIZE_PATH: "GAME_STATE_SET_OPTIMIZE_PATH",
    GAME_STATE_SET_NODE_POSITION: "GAME_STATE_SET_NODE_POSITION",
    GAME_STATE_SET_VISUALIZE_FINDING: "GAME_STATE_SET_VISUALIZE_FINDING",
    GAME_STATE_SET_WALL_POSITION: "GAME_STATE_SET_WALL_POSITION",
    WALL_POSITION_TEMPLATE_STATE_SET_IS_SELECTED: "WALL_POSITION_TEMPLATE_STATE_SET_IS_SELECTED",
    WALL_POSITION_TEMPLATE_STATE_RESTORE_DATA: "WALL_POSITION_TEMPLATE_STATE_RESTORE_DATA",
});

export default ActionEnums;